export const subtitles = [
  "secção, desk support, 2019",
  "",
  "+cinco, tableware, 2014",
  "coleção 35, coffee table, 2019",
  "",
  "pamela mesquita, business card, 2019",
  "miguel lopes, business card, 2019",
  "cónico, merino wool, 2019",
  "gastroco office, interior design, 2020",
  "",
  "timeless garage, brand identity, 2019",
  "",
  "",
  "ballard, brand identity, 2019",
  "",
  "",
  "unicorn, brand identity, 2019",
  "",
  "",
  "derinda brown, brand identity, 2020",
  "",
  "janine, brand identity, 2020",
  "",
  ""
];
