export const subtitles = [
  "Brand Identity, Ballard Audio",
  "Ballard Audio",
  "Brand Identity, Ballard Audio",
  "Poster, Ballard Audio",
  "App, Ballard Audio",
  "Brand Identity, Unicorn Legal",
  "Brand Identity, Unicorn Legal",
  "Posters, Unicorn Legal",
  "Website, Unicorn Legal",
  "Folders, Unicorn Legal",
  "Unicorn Legal",
  "Brand Identity, Timeless Garage",
  "Brand Identity, Timeless Garage",
  "Brand Identity, Timeless Garage",
  "Brand Identity, Timeless Garage",
  "Custom Land Rover, Timeless Garage",
  "Brochure, Timeless Garage",
  "Digital Poster, Timeless Garage",
  "Brand Identity, André Malheiro",
  "Brand Identity, André Malheiro",
  "Website, André Malheiro",
  "Website, André Malheiro",
  "Product Design, Secção",
  "Product Design, Secção",
  "Personal Business Card",
  "Business Card, Pamela Mesquita",
  "Brand Identity, Caprichar",
  "Brand Identity, Caprichar",
  "Brand Identity, Caprichar",
  "Bath Soaps, Caprichar",
  "Packaging, Caprichar",
  "Brand Identity, Caprichar",
  "Brand Identity, Caprichar",
  "Brand Identity, Rats & Bananas",
  "Brand Identity, Rats & Bananas",
  "Brand Identity, Rats & Bananas",
  "Magazine, Rats & Bananas",
  "On-line Store, Rats & Bananas",
  "Brand Identity, Raffaelle Sarubbo",
  "Brand Identity, Raffaelle Sarubbo",
  "Brand Identity, Raffaelle Sarubbo",
  "Social Media, Raffaelle Sarubbo",
  "Brand Identity, HO Wine House of Colares",
];