export const subtitles = [
  "Secção, desk support, 2019",
  "",
  "+cinco, tableware, 2014",
  "Coleção 35, coffee table, 2019",
  "",
  "Pamela Mesquita, business card, 2019",
  "Miguel Lopes, business card, 2019",
  "Cónico, merino wool, 2019",
  "Timeless Garage, brand identity, 2019",
  "",
  "",
  "",
  "",
  "Unicorn, brand identity, 2019",
  "",
  "",
  "",
  "",
  "Ballard, brand identity, 2019",
  "",
  "",
  "Janine, brand identity, 2020",
  "",
  "",
  "André Malheiro, brand identity, 2019",
  "",
  "",
  "Derinda Brown, brand identity, 2020",
  "",
  "",
  "",
  "",
];
